name: Build and Push Docker Image

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:
    schedule:
        # Daily re-build to ensure the image stays fresh with security updates
        - cron: '0 0 * * *'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

            - name: Log in to GitHub Container Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                    # Set latest tag for main branch
                    type=raw,value=latest,enable={{is_default_branch}}
                    # Set edge tag for main branch
                    type=edge,branch=main
                    # Git short SHA
                    type=sha,prefix={{branch}}-
                    # Date-based tag
                    type=schedule,pattern={{date 'YYYYMMDD'}}
                    # Semantic versioning (if using tags)
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=semver,pattern={{major}}
                labels: |
                    org.opencontainers.image.title=ARMCortexM-CppLib Development Environment
                    org.opencontainers.image.source=https://github.com/MatejGomboc/ARMCortexM-CppLib-DevEnv
                    org.opencontainers.image.description=Development environment for ARMCortexM-CppLib
                    org.opencontainers.image.vendor=MatejGomboc
                    org.opencontainers.image.licenses=Apache-2.0
                    org.opencontainers.image.authors=MatejGomboc <https://github.com/MatejGomboc>

            - name: Build and push Docker image
              id: build
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: linux/amd64
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Generate artifact attestation
              if: github.event_name != 'pull_request'
              uses: actions/attest-build-provenance@v3
              with:
                subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                subject-digest: ${{ steps.build.outputs.digest }}
                push-to-registry: true
